
AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassVars:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20
  Severity: refactor

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 50